
<section class="createclient">
	<h1>Vous êtes un nouveau client ?</h1>
	<form method="POST">
		<input type="texte" name="pseudo" placeholder="Pseudo">
		<input type="password" name="mdp" placeholder="Mot de passe">
		<input type="texte" name="nom" placeholder="Nom">
		<input type="texte" name="prenom" placeholder="Prénom">
		<input type="texte" name="adresse" placeholder="Adresse">
		<input type="texte" name="ville" placeholder="Ville">
		<input type="texte" name="telephone" placeholder="Téléphone">
		<input type="texte" name="email" placeholder="Email">
		<button name="action" value="create">Crée un compte client</button>
	</form>
</section>
