<footer>
    <div class="fonts">
        <a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-snapchat" aria-hidden="true"></i></a>
    </div>
    <p>
        Mention légale 2017
    </p>
</footer>