<header>
	<h1><a href="index.php">Feelgood</a></h1>
	<p>Des sacs colorés et bohème chics, parfaits pour le quotidien</p>
	<ul>
		<li><a href="index.php"><i class="fa fa-heart" aria-hidden="true"></i></i>Nouvelle collection</a></li>
		<li><a href="index.php?page=create"><i class="fa fa-user-circle-o" aria-hidden="true"></i></i>Nouveau client</a></li>
		<li><a href="index.php?page=connexion"><i class="fa fa-key" aria-hidden="true"></i></i>Se connecter</a></li>
		<li><a href=""><i class="fa fa-shopping-bag" aria-hidden="true"></i>Mon panier</a></li>
	</ul>
</header>
<hr>

