<div class="detail_produit">
	<article>
		<h2 class="nom_produit"><?=htmlentities($produit->getNomProduit())?></h2>
		<img src="<?=$produit->getImage()?>"/>
		<div>
			<p class="description_produit">Description du produit :<br><?=htmlentities($produit->getDescriptionProduit())?></p>
			<p class="prix"><?=htmlentities($produit->getPrix())?> €</p>
			<p class="quantite"><?=htmlentities($produit->getQuantite())?> pièce(s) en stock</p>
			<p class="couleur">Couleur : <?=htmlentities($produit->getCouleur())?></p>
			<p class="gamme">Type : <?=htmlentities($produit->getGamme())?></p>
		</div>
	
	<form method="POST" action="index.php?page=panier">
		<input type="hidden" name="id_produit" value="<?=intval($produit->getId())?>">
		<button type="submit" name="action" value="ajouter"><i class="fa fa-shopping-bag" aria-hidden="true"></i>Ajouter au panier</button>
	</form>
		
	</article class="description">
			
		<form method="POST">
		<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">
		<div>
			<textarea name="description" placeholder="Avis"></textarea>
		</div>
		<button name="action" value="create">Envoyer</button>
	</form>
	
	<?php
		foreach ($produit->getCommentaires() AS $commentaire)
		{?>
			<article>
				<hr>
				Ecrit par <span><?=htmlentities($commentaire->getAuteur()->getPseudo())?></span> le <span><?=htmlentities($commentaire->getDate())?></span>
				<div>
					<?=nl2br(htmlentities($commentaire->getDescription()))?>
				</div>
			</article>
		<?php
		}
	?>
</div>