<form class="form-horizontal" method="POST">
	<input type="text" name="nom_produit" placeholder="nom du produit">
	<input type="url" name="image" placeholder="image">
	<textarea name="description_produit" placeholder="description du produit"></textarea>
	<input type="text" name="prix" placeholder="prix du produit">
	<input type="text" name="quantite" placeholder="quantitié du produit">
	<input type="text" name="couleur" placeholder="couleur du produit">
	<input type="text" name="gamme" placeholder="gamme du produit">
	<button name="action" value="create">Create</button>
</form>