<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Reenie+Beanie" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="public/styles/font-awesome.min.css"/>
    <link rel="stylesheet" href="./public/styles/styles.css" />
    <meta charset="UTF-8">
    <title>Feelgood</title>
</head>
<body>
	<?php require('apps/header.php'); ?>
	<?php require('apps/content.php'); ?>
	<?php require('apps/footer.php'); ?>
</body>
</html> 